[neptune]
profiles = stable
keywords = -VisibleVcsPkg,-PotentialStable,-UnderscoreInUseFlag,-TotalSizeViolation,-MatchingChksums,-VirtualWithSingleProvider,-RedundantVersion,-UnknownRestrict,-ExcessiveLineLength,-RequiredUseDefaults,-SizeViolation,-ReferenceInMetadataVar
