[neptune]
profiles = stable
keywords = -PotentialStable,-UnderscoreInUseFlag,-TotalSizeViolation,-MatchingChksums,-VirtualWithSingleProvider,-RedundantVersion,-UnknownRestrict,-ExcessiveLineLength,-RequiredUseDefaults,-SizeViolation
