[neptune]
profiles = stable
keywords = -UnderscoreInUseFlag,-TotalSizeViolation,-MatchingChksums,-VirtualWithSingleProvider,-UnusedGlobalUseExpand,-PythonCompatUpdate,-NonsolvableDepsInDev,-NonsolvableDepsInStable,-VisibleVcsPkg,-AbsoluteSymlink,-RedundantVersion,-UnknownRestrict,-ExcessiveLineLength,-RequiredUseDefaults,-SizeViolation,-ReferenceInMetadataVar
