# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

CRATES="
	ahash@0.8.11
	aho-corasick@1.1.3
	allocator-api2@0.2.18
	android_system_properties@0.1.5
	arrayvec@0.7.6
	ash@0.38.0+1.3.281
	autocfg@1.4.0
	bindgen@0.70.1
	bit-set@0.8.0
	bit-vec@0.8.0
	bitflags@1.3.2
	bitflags@2.8.0
	block@0.1.6
	bumpalo@3.16.0
	bytemuck@1.21.0
	bytemuck_derive@1.8.1
	cexpr@0.6.0
	cfg-if@1.0.0
	cfg_aliases@0.2.1
	clang-sys@1.8.1
	codespan-reporting@0.11.1
	core-foundation-sys@0.8.7
	core-foundation@0.9.4
	core-graphics-types@0.1.3
	document-features@0.2.10
	either@1.13.0
	equivalent@1.0.1
	fixedbitset@0.5.7
	foreign-types-macros@0.2.3
	foreign-types-shared@0.3.1
	foreign-types@0.5.0
	gl_generator@0.14.0
	glob@0.3.1
	glow@0.16.0
	glutin_wgl_sys@0.6.0
	gpu-alloc-types@0.3.0
	gpu-alloc@0.6.0
	gpu-allocator@0.27.0
	gpu-descriptor-types@0.2.0
	gpu-descriptor@0.3.0
	hashbrown@0.14.5
	hashbrown@0.15.0
	heck@0.5.0
	hexf-parse@0.2.1
	indexmap@2.6.0
	itertools@0.13.0
	jni-sys@0.3.0
	js-sys@0.3.77
	khronos-egl@6.0.0
	khronos_api@3.1.0
	libc@0.2.159
	libloading@0.8.5
	litrs@0.4.1
	lock_api@0.4.12
	log@0.4.22
	malloc_buf@0.0.6
	memchr@2.7.4
	metal@0.31.0
	minimal-lexical@0.2.1
	ndk-sys@0.5.0+25.2.9519653
	nom@7.1.3
	num-traits@0.2.19
	objc@0.2.7
	once_cell@1.20.2
	ordered-float@4.6.0
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	paste@1.0.15
	petgraph@0.7.1
	pkg-config@0.3.31
	pp-rs@0.2.1
	presser@0.3.1
	prettyplease@0.2.22
	proc-macro2@1.0.87
	profiling@1.0.15
	quote@1.0.37
	range-alloc@0.1.3
	raw-window-handle@0.6.2
	redox_syscall@0.5.7
	regex-automata@0.4.8
	regex-syntax@0.8.5
	regex@1.11.0
	renderdoc-sys@1.1.0
	rustc-hash@1.1.0
	rustversion@1.0.19
	scopeguard@1.2.0
	serde@1.0.217
	serde_derive@1.0.217
	shlex@1.3.0
	slotmap@1.0.7
	smallvec@1.13.2
	spirv@0.3.0+sdk-1.3.268.0
	strum@0.26.3
	strum_macros@0.26.4
	syn@2.0.87
	termcolor@1.4.1
	thiserror-impl@1.0.69
	thiserror-impl@2.0.11
	thiserror@1.0.69
	thiserror@2.0.11
	unicode-ident@1.0.13
	unicode-width@0.1.14
	unicode-xid@0.2.6
	version_check@0.9.5
	wasm-bindgen-backend@0.2.100
	wasm-bindgen-macro-support@0.2.100
	wasm-bindgen-macro@0.2.100
	wasm-bindgen-shared@0.2.100
	wasm-bindgen@0.2.100
	web-sys@0.3.77
	winapi-util@0.1.9
	windows-core@0.58.0
	windows-implement@0.58.0
	windows-interface@0.58.0
	windows-result@0.2.0
	windows-strings@0.1.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows@0.58.0
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	xml-rs@0.8.22
	zerocopy-derive@0.7.35
	zerocopy@0.7.35
"

declare -A GIT_CRATES=(
	[naga]='https://github.com/gfx-rs/wgpu;779261e64daa6cf76c826532b7a1561d8ec203fd;wgpu-%commit%/naga'
	[wgpu-core]='https://github.com/gfx-rs/wgpu;779261e64daa6cf76c826532b7a1561d8ec203fd;wgpu-%commit%/wgpu-core'
	[wgpu-hal]='https://github.com/gfx-rs/wgpu;779261e64daa6cf76c826532b7a1561d8ec203fd;wgpu-%commit%/wgpu-hal'
	[wgpu-types]='https://github.com/gfx-rs/wgpu;779261e64daa6cf76c826532b7a1561d8ec203fd;wgpu-%commit%/wgpu-types'
)

inherit cargo

DESCRIPTION="Native WebGPU implementation based on wgpu-core"
HOMEPAGE="https://github.com/gfx-rs/wgpu-native"
COMMIT="f29ebee88362934f8f9fab530f3ccb7fde2d49a9"
SRC_URI="
	https://github.com/gfx-rs/wgpu-native/archive/${COMMIT}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
S="${WORKDIR}/${PN}-${COMMIT}"

BDEPEND="
	dev-util/webgpu-headers:=
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD CC0-1.0 ISC MIT Unicode-DFS-2016 ZLIB"
SLOT="0"
KEYWORDS="~amd64"

PATCHES=(
	"${FILESDIR}/wgpu-native-24.0.0-version.patch"
)

src_prepare() {
	default

	rmdir ffi/webgpu-headers
	ln -s "${EPREFIX}/usr/include/webgpu" ffi/webgpu-headers
}

src_install() {
	dolib.a "$(cargo_target_dir)/libwgpu_native.a"
	dolib.so "$(cargo_target_dir)/libwgpu_native.so"
	doheader ffi/wgpu.h
}
