# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.4

EAPI=8

CRATES="
	autocfg@1.1.0
	bitflags@1.3.2
	byteorder@1.4.3
	cfg-if@1.0.0
	console_engine@2.5.0
	crossterm@0.24.0
	crossterm_winapi@0.9.0
	libc@0.2.132
	libpulse-binding@2.26.0
	libpulse-simple-binding@2.25.0
	libpulse-simple-sys@1.19.2
	libpulse-sys@1.19.3
	lock_api@0.4.6
	log@0.4.14
	mio@0.8.4
	num-complex@0.4.0
	num-derive@0.3.3
	num-integer@0.1.44
	num-traits@0.2.14
	parking_lot@0.12.0
	parking_lot_core@0.9.1
	pkg-config@0.3.24
	primal-check@0.3.1
	proc-macro2@1.0.36
	quote@1.0.15
	realfft@3.0.1
	redox_syscall@0.2.11
	rubato@0.12.0
	rustfft@6.0.1
	scopeguard@1.1.0
	signal-hook-mio@0.2.3
	signal-hook-registry@1.4.0
	signal-hook@0.3.13
	smallvec@1.8.0
	strength_reduce@0.2.3
	syn@1.0.86
	transpose@0.2.1
	unicode-width@0.1.9
	unicode-xid@0.2.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.32.0
	windows-sys@0.36.1
	windows_aarch64_msvc@0.32.0
	windows_aarch64_msvc@0.36.1
	windows_i686_gnu@0.32.0
	windows_i686_gnu@0.36.1
	windows_i686_msvc@0.32.0
	windows_i686_msvc@0.36.1
	windows_x86_64_gnu@0.32.0
	windows_x86_64_gnu@0.36.1
	windows_x86_64_msvc@0.32.0
	windows_x86_64_msvc@0.36.1
"

inherit cargo

DESCRIPTION="A multiplatform terminal-based audio visualizer written in Rust"
HOMEPAGE="https://github.com/natty-misc/mizu-vizu"
SRC_URI="
	https://github.com/natty-misc/mizu-vizu/archive/ee6572c74f9aabb2827210f0d297d79389ea8eaf.tar.gz -> ${PN}-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"
S="${WORKDIR}/mizu-vizu-ee6572c74f9aabb2827210f0d297d79389ea8eaf"

LICENSE="|| ( GPL-3 MIT )"
# Dependent crate licenses
LICENSE+=" MIT"
SLOT="0"
KEYWORDS="~amd64"
