# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

inherit cargo git-r3

DESCRIPTION="A parser for Microsoft PDB (Program Database) debugging information"
HOMEPAGE="https://github.com/Vector35/pdb-rs"
EGIT_REPO_URI="https://github.com/neptuwunium/pdb-rs.git"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" MIT"
SLOT="0"

RDEPEND="
	!dev-util/pdb-rs
"

BDEPEND="
	!dev-util/pdb-rs
"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}

src_prepare() {
	default

	mv examples/pdb_lines.rs examples/pdb-lines.rs
	mv examples/pdb_framedata.rs examples/pdb-framedata.rs
	mv examples/pdb_symbols.rs examples/pdb-symbols.rs
	mv examples/stream_names.rs examples/pdb-stream-names.rs
}

src_configure() {
	cargo_src_configure --frozen
}

src_compile() {
	cargo_src_compile --examples
}

src_install() {
	cargo_src_install --examples
}
