# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

inherit cargo git-r3

DESCRIPTION="Steam Achievement Manager Rewritten"
HOMEPAGE="https://github.com/PaulCombal/SamRewritten/"
EGIT_REPO_URI="https://github.com/PaulCombal/SamRewritten.git"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+="
	0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD ISC MIT
	Unicode-3.0
"
SLOT="0"
KEYWORDS="~amd64"

src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}
