# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8


CRATES="
	aho-corasick@1.1.3
	ansi_term@0.12.1
	atty@0.2.14
	aws-lc-rs@1.7.1
	aws-lc-sys@0.16.0
	base64@0.22.1
	bindgen@0.69.4
	bitflags@2.5.0
	byteorder@1.5.0
	cc@1.2.16
	cexpr@0.6.0
	cfg-if@1.0.0
	clang-sys@1.7.0
	cmake@0.1.50
	core-foundation-sys@0.8.6
	core-foundation@0.9.4
	datetime@0.5.2
	diff@0.1.13
	doge_dns@1.0.2
	doge_transport@0.2.6
	dunce@1.0.4
	either@1.11.0
	errno@0.3.8
	fastrand@2.1.0
	foreign-types-shared@0.1.1
	foreign-types@0.3.2
	fs_extra@1.3.0
	getopts@0.2.21
	getrandom@0.2.15
	getrandom@0.3.0
	glob@0.3.1
	hermit-abi@0.1.19
	home@0.5.9
	httparse@1.8.0
	ipconfig@0.3.2
	itertools@0.12.1
	jobserver@0.1.31
	json@0.12.4
	lazy_static@1.4.0
	lazycell@1.3.0
	libc@0.2.170
	libloading@0.8.3
	linux-raw-sys@0.4.13
	log@0.4.27
	matches@0.1.10
	memchr@2.7.2
	minimal-lexical@0.2.1
	mirai-annotations@1.12.0
	native-tls@0.2.11
	nom@7.1.3
	once_cell@1.19.0
	openssl-macros@0.1.1
	openssl-probe@0.1.5
	openssl-src@300.2.3+3.2.1
	openssl-sys@0.9.107
	openssl@0.10.72
	paste@1.0.14
	pkg-config@0.3.30
	ppv-lite86@0.2.17
	pretty_assertions@1.4.1
	prettyplease@0.2.19
	proc-macro2@1.0.81
	quote@1.0.36
	rand@0.9.1
	rand_chacha@0.9.0
	rand_core@0.9.0
	redox_syscall@0.1.57
	regex-automata@0.4.6
	regex-syntax@0.8.3
	regex@1.10.4
	ring@0.17.13
	rustc-hash@1.1.0
	rustix@0.38.34
	rustls-pki-types@1.5.0
	rustls-webpki@0.102.3
	rustls@0.23.5
	schannel@0.1.23
	security-framework-sys@2.11.0
	security-framework@2.11.0
	shlex@1.3.0
	socket2@0.5.7
	subtle@2.5.0
	syn@2.0.60
	tempfile@3.10.1
	unic-char-property@0.9.0
	unic-char-range@0.9.0
	unic-common@0.9.0
	unic-idna-mapping@0.9.0
	unic-idna-punycode@0.9.0
	unic-idna@0.9.0
	unic-normal@0.9.0
	unic-ucd-bidi@0.9.0
	unic-ucd-hangul@0.9.0
	unic-ucd-normal@0.9.0
	unic-ucd-version@0.9.0
	unicode-ident@1.0.12
	unicode-width@0.1.12
	untrusted@0.9.0
	vcpkg@0.2.15
	wasi@0.11.0+wasi-snapshot-preview1
	wasi@0.13.3+wasi-0.2.2
	webpki-roots@0.26.1
	webpki@0.22.4
	which@4.4.2
	widestring@1.1.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.5
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.5
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.5
	windows_i686_gnullvm@0.52.5
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.5
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.5
	winreg@0.50.0
	wit-bindgen-rt@0.33.0
	yansi@1.0.1
	zerocopy-derive@0.8.14
	zerocopy@0.8.14
	zeroize@1.7.0
"

RUST_MIN_VER="1.80.1"

inherit cargo

DESCRIPTION="A command-line DNS client"
HOMEPAGE="https://github.com/Dj-Codeman/dog_community"
SRC_URI="
	https://github.com/Dj-Codeman/dog_community/archive/refs/tags/v${PV}.tar.gz -> ${CATEGORY}-${PN}-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"
S="${WORK_DIR}/dog_community-${PV}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD ISC MIT MPL-2.0 openssl Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64 ~arm64"
