# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

CRATES="
	fallible-iterator@0.2.0
	getopts@0.2.21
	scroll@0.11.0
	unicode-width@0.1.5
	uuid@1.0.0
"

inherit cargo

DESCRIPTION="A parser for Microsoft PDB (Program Database) debugging information"
HOMEPAGE="https://github.com/Vector35/pdb-rs"
SRC_URI="
	https://github.com/Vector35/pdb-rs/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

src_prepare() {
	default

	mv examples/pdb_lines.rs examples/pdb-lines.rs
	mv examples/pdb_framedata.rs examples/pdb-framedata.rs
	mv examples/pdb_symbols.rs examples/pdb-symbols.rs
	mv examples/stream_names.rs examples/pdb-stream-names.rs
}

src_compile() {
	cargo_src_compile --examples
}

src_install() {
	cargo_src_install --examples
}
